name: Deploy Docker

on:
    push:
        branches: ["prod"]

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Decode ACCOUNT_SERVICE from Secret
              run: |
                  cd FPTPlaygroundServer
                  mkdir -p Credentials  # Create folder "Credentials" if not exist
                  echo "${{ secrets.ACCOUNT_SERVICE }}" | base64 --decode > Credentials/account_service.json

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build Docker image and push
              run: |
                  docker buildx build . \
                      --file FPTPlaygroundServer/Dockerfile \
                      --tag kietmaster2003/fptplayground-prod \
                      --push \
                      --build-arg DB_POSTGRES_CONNECTION_STRING="${{ secrets.DB_POSTGRES_CONNECTION_STRING }}" \
                      --build-arg DB_REDIS_CONNECTION_STRING="${{ secrets.DB_REDIS_CONNECTION_STRING }}" \
                      --build-arg JWT_ISSUER="${{ secrets.JWT_ISSUER }}" \
                      --build-arg JWT_AUDIENCE="${{ secrets.JWT_AUDIENCE }}" \
                      --build-arg JWT_SIGNING_KEY="${{ secrets.JWT_SIGNING_KEY }}" \
                      --build-arg SMTP_MAIL="${{ secrets.SMTP_MAIL }}" \
                      --build-arg SMTP_PASSWORD="${{ secrets.SMTP_PASSWORD }}" \
                      --build-arg PAYOS_CLIENT_ID="${{ secrets.PAYOS_CLIENT_ID }}" \
                      --build-arg PAYOS_API_KEY="${{ secrets.PAYOS_API_KEY }}" \
                      --build-arg PAYOS_CHECKSUM_KEY="${{ secrets.PAYOS_CHECKSUM_KEY }}" \
                      --build-arg GOOGLE_STORAGE_BUCKET="${{ secrets.GOOGLE_STORAGE_BUCKET }}"